// FILE GENERATED BY scripts/update-cli.sh - DO NOT MODIFY BY HAND

import 'package:sentry_dart_plugin/src/cli/sources.dart';

import 'host_platform.dart';

const _version = '2.36.5';

final currentCLISources = {
  HostPlatform.darwinUniversal: CLISource(
    'sentry-cli-Darwin-universal',
    _version,
    '10aaef60223c497839f89dd2d5ea79fc801dddca712898ef0cd4290a4c004b1a',
  ),
  HostPlatform.linuxAarch64: CLISource(
    'sentry-cli-Linux-aarch64',
    _version,
    '633f4859816d18e288563cd60d5027804be4e61da27191e846f24ba52c30e20a',
  ),
  HostPlatform.linuxArmv7: CLISource(
    'sentry-cli-Linux-armv7',
    _version,
    '6375575a256a07d1dd9315c7e02847b7cfe998bf5be99b8863389470a64330e2',
  ),
  HostPlatform.linux64bit: CLISource(
    'sentry-cli-Linux-x86_64',
    _version,
    '5696cb1eb0238190b86f18ac2036f89524bfdb2ecd12d1a11a488d2e93fb5024',
  ),
  HostPlatform.windows32bit: CLISource(
    'sentry-cli-Windows-i686.exe',
    _version,
    '494a97fa76f7536d4488eaec237b7487b71e14dfcb50b7beff2e2b979ef017f7',
  ),
  HostPlatform.windows64bit: CLISource(
    'sentry-cli-Windows-x86_64.exe',
    _version,
    'bfa521d59668931503bfa23e5069a741b6171f0ba52783f1ba6b6d44d6cddb31',
  ),
};
