// FILE GENERATED BY scripts/update-cli.sh - DO NOT MODIFY BY HAND

import 'package:sentry_dart_plugin/src/cli/sources.dart';

import 'host_platform.dart';

const _version = '2.17.5';
const _urlPrefix = 'https://downloads.sentry-cdn.com/sentry-cli/$_version';

final currentCLISources = {
  HostPlatform.darwinUniversal: CLISource(
      '$_urlPrefix/sentry-cli-Darwin-universal',
      '7586993d8a686dfb3e42f81075e6cc44cfcc8e6b07b207b5e067a26e914c58a3'),
  HostPlatform.linuxAarch64: CLISource('$_urlPrefix/sentry-cli-Linux-aarch64',
      '2071c03f870fcce6f9e82cefcff004e92f6d1af250a31d157ba921c671a5f9ec'),
  HostPlatform.linuxArmv7: CLISource('$_urlPrefix/sentry-cli-Linux-armv7',
      '260c4dfc70a398d4c9993b5c51fe8eb44200cbbe2cdfc0cfedaf7980fe21ee11'),
  HostPlatform.linux64bit: CLISource('$_urlPrefix/sentry-cli-Linux-x86_64',
      '8200b8f0831535d5c21adfde947ca6d30930619eae36a650cbcf1005c68cd6dd'),
  HostPlatform.windows32bit: CLISource(
      '$_urlPrefix/sentry-cli-Windows-i686.exe',
      '718209c411305dc4d86676dba6bef09e7c69bce03ce457c09f3b05ae08e1126e'),
  HostPlatform.windows64bit: CLISource(
      '$_urlPrefix/sentry-cli-Windows-x86_64.exe',
      '4ee6d34cce58bed122acc1602d327c28c9b82fa9e64bcc73100012e644e6537a'),
};
