name: "Danger"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Changelog
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
